#!/usr/bin/env ruby
# / Usage: prime_table [options]
# / -n   N number of prime, default: 10
# / -t   Table size, default: 10

$stdout = STDOUT
require 'optparse'
require './lib/prime_number'
require './lib/number_table'

# default options
number = 10
table_size = 10

ARGV.options do |opts|
  opts.on('-n')                 { number = ARGV[0] }
  opts.on('-t')                 { table_size = ARGV[0] }
  opts.on_tail('-h', '--help')  { exec "grep ^#/<'#{__FILE__}'|cut -c4-" }
  opts.parse!
end

# initialize classes
prime_number = PrimeNumber.new(number)
number_table = NumberTable.new(table_size)

# print table header
puts number_table.header

# calculate next prime, loop if prime number is given
while prime_number.calculate_next_prime_if_eligible

  # print table row
  puts number_table.row(prime_number.current_prime)
end
